boot:
	nasm -f bin boot.asm -o boot.bin

test:
	nasm -f bin test.asm -o test.bin

mbr_loader:
	nasm -f bin mbr_loader.asm -o mbr_loader.bin

show_char:
	nasm -f bin show_char.asm -o show_char.bin

clean:
	rm *.bin